#### Import the package

In [2]:
import numpy as np

#### Create the arrays

In [4]:
x = np.array([56,22,15,37,68,89,26])

In [5]:
print(x)

[56 22 15 37 68 89 26]


In [6]:
type(x)

numpy.ndarray

In [7]:
x[3]

37

In [8]:
x[3] = 45
x

array([56, 22, 15, 45, 68, 89, 26])

In [9]:
y = np.array([56, 22, 15, 37, 68.54, 89, 26])

In [10]:
y

array([56.  , 22.  , 15.  , 37.  , 68.54, 89.  , 26.  ])

In [11]:
y.dtype

dtype('float64')

In [12]:
x.dtype

dtype('int64')

In [13]:
x.shape

(7,)

In [14]:
x.ndim

1

In [15]:
x.min()

15

In [16]:
x.max()

89

In [18]:
x.sort()
x

array([15, 22, 26, 45, 56, 68, 89])

In [19]:
x

array([15, 22, 26, 45, 56, 68, 89])

In [20]:
x + 3

array([18, 25, 29, 48, 59, 71, 92])

In [21]:
x - 12

array([ 3, 10, 14, 33, 44, 56, 77])

In [22]:
x / 12

array([1.25      , 1.83333333, 2.16666667, 3.75      , 4.66666667,
       5.66666667, 7.41666667])

In [23]:
a = np.array([4,4,6,8,2,1])
b = np.array([7,2,4,3,9,8])

In [24]:
a + b

array([11,  6, 10, 11, 11,  9])

In [25]:
len(x)

7

In [26]:
x.shape

(7,)

In [32]:
z = np.array([[5,7,8],[2,1,4]])

In [33]:
z

array([[5, 7, 8],
       [2, 1, 4]])

In [34]:
z.shape

(2, 3)

In [35]:
z.size

6

In [36]:
z.dtype

dtype('int64')

In [37]:
t = z.reshape(3,2)

In [38]:
t

array([[5, 7],
       [8, 2],
       [1, 4]])

In [39]:
z.reshape(6,1)

array([[5],
       [7],
       [8],
       [2],
       [1],
       [4]])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [42]:
np.arange(4,15,2)

array([ 4,  6,  8, 10, 12, 14])

In [43]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])